name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  bucket-name: 
    description: 'Name of the bucket to use'
    required: true
  dist-folder:
    description: 'Name of the folder to use'
    required: false
  SUPABASE_URL:
    description: 'Base URL of the application'
    required: true
  SUPABASE_ANON_KEY:
    description: 'Anonymous key of the application'
    required: true
outputs:
  result:
    description: 'Media Key for the image'
runs:
  using: 'node16'
  main: 'index.js'
